- name: Disable NodeJS Default Version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS 20 Version
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Add Expense User
  ansible.builtin.user:
    name: expense
    state: present

- name: Copy Backend Service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Delete existing application Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application  Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download frontend content & extract
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
    dest: /app
    remote_src: true

- name: Download NodeJS App Dependencies
  community.general.npm:
    path: /app

- name: Install MySQL client & MYSQL Python Module
  ansible.builtin.dnf:
    name:
      - mysql
      - python3-PyMySQL
    state: present

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.ankitguptarbr08.online

- name: Start Backend Service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: true
    daemon_reload: true

